// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANfcjOPwQSs5zl4OZcfwnbzQayjc05sJw',
    appId: '1:1094962767456:web:11422344188cf7d8534505',
    messagingSenderId: '1094962767456',
    projectId: 'study-loop-8acb8',
    authDomain: 'study-loop-8acb8.firebaseapp.com',
    storageBucket: 'study-loop-8acb8.firebasestorage.app',
    measurementId: 'G-8JJ73PVTEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFDTj8JMwm3Nq_JECVDtJ77CJn34VuaM4',
    appId: '1:1094962767456:android:9be3e89e2ba108a7534505',
    messagingSenderId: '1094962767456',
    projectId: 'study-loop-8acb8',
    storageBucket: 'study-loop-8acb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqf-dh4ktQR052fsGz3oLx5PWJCjY5As',
    appId: '1:1094962767456:ios:60e9105b8a672283534505',
    messagingSenderId: '1094962767456',
    projectId: 'study-loop-8acb8',
    storageBucket: 'study-loop-8acb8.firebasestorage.app',
    iosBundleId: 'com.example.reviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqf-dh4ktQR052fsGz3oLx5PWJCjY5As',
    appId: '1:1094962767456:ios:60e9105b8a672283534505',
    messagingSenderId: '1094962767456',
    projectId: 'study-loop-8acb8',
    storageBucket: 'study-loop-8acb8.firebasestorage.app',
    iosBundleId: 'com.example.reviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANfcjOPwQSs5zl4OZcfwnbzQayjc05sJw',
    appId: '1:1094962767456:web:b68e3ba058a5647d534505',
    messagingSenderId: '1094962767456',
    projectId: 'study-loop-8acb8',
    authDomain: 'study-loop-8acb8.firebaseapp.com',
    storageBucket: 'study-loop-8acb8.firebasestorage.app',
    measurementId: 'G-SHSPQRKMLK',
  );
}
